spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app-dev
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: my_user
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: 127.0.0.1
    port: 6379
  security:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expired: 86400000